name: URL health check

on:
  schedule:
    - cron: '15 * * * *'
    
jobs: 
  healthCheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed Pokedex URL
        uses: jtalk/url-health-check-action@v3
        with:
          # Check the following URLs one by one sequentially
          url: https://axunpokedex.onrender.com/health
